#include "keymap.h"

using namespace clench::wsal;

CLCWSAL_API const std::map<UINT, KeyboardKeyCode> clench::wsal::g_win32KeyMap = {
	{ VK_SPACE, (KeyboardKeyCode)' ' },
	{ VK_OEM_7, (KeyboardKeyCode)'\'' },
	{ ',', (KeyboardKeyCode)',' },
	{ '-', (KeyboardKeyCode)'-' },
	{ '.', (KeyboardKeyCode)'.' },
	{ '/', (KeyboardKeyCode)'/' },

	{ '0', (KeyboardKeyCode)'0' },
	{ '1', (KeyboardKeyCode)'1' },
	{ '2', (KeyboardKeyCode)'2' },
	{ '3', (KeyboardKeyCode)'3' },
	{ '4', (KeyboardKeyCode)'4' },
	{ '5', (KeyboardKeyCode)'5' },
	{ '6', (KeyboardKeyCode)'6' },
	{ '7', (KeyboardKeyCode)'7' },
	{ '8', (KeyboardKeyCode)'8' },
	{ '9', (KeyboardKeyCode)'9' },

	{ ';', (KeyboardKeyCode)';' },
	{ '=', (KeyboardKeyCode)'=' },

	{ 'A', (KeyboardKeyCode)'A' },
	{ 'B', (KeyboardKeyCode)'B' },
	{ 'C', (KeyboardKeyCode)'C' },
	{ 'D', (KeyboardKeyCode)'D' },
	{ 'E', (KeyboardKeyCode)'E' },
	{ 'F', (KeyboardKeyCode)'F' },
	{ 'G', (KeyboardKeyCode)'G' },
	{ 'H', (KeyboardKeyCode)'H' },
	{ 'I', (KeyboardKeyCode)'I' },
	{ 'J', (KeyboardKeyCode)'J' },
	{ 'K', (KeyboardKeyCode)'K' },
	{ 'L', (KeyboardKeyCode)'L' },
	{ 'M', (KeyboardKeyCode)'M' },
	{ 'N', (KeyboardKeyCode)'N' },
	{ 'O', (KeyboardKeyCode)'O' },
	{ 'P', (KeyboardKeyCode)'P' },
	{ 'Q', (KeyboardKeyCode)'Q' },
	{ 'R', (KeyboardKeyCode)'R' },
	{ 'S', (KeyboardKeyCode)'S' },
	{ 'T', (KeyboardKeyCode)'T' },
	{ 'U', (KeyboardKeyCode)'U' },
	{ 'V', (KeyboardKeyCode)'V' },
	{ 'W', (KeyboardKeyCode)'W' },
	{ 'X', (KeyboardKeyCode)'X' },
	{ 'Y', (KeyboardKeyCode)'Y' },
	{ 'Z', (KeyboardKeyCode)'Z' },

	{ VK_OEM_4, (KeyboardKeyCode)'[' },
	{ VK_OEM_5, (KeyboardKeyCode)'\\' },
	{ VK_OEM_6, (KeyboardKeyCode)']' },
	{ '^', (KeyboardKeyCode)'^' },
	{ '_', (KeyboardKeyCode)'_' },
	{ '`', (KeyboardKeyCode)'`' },

	{ '{', (KeyboardKeyCode)'{' },
	{ '|', (KeyboardKeyCode)'|' },
	{ '}', (KeyboardKeyCode)'}' },
	{ '~', (KeyboardKeyCode)'~' },

	{ VK_BACK, KeyboardKeyCode::Backspace },
	{ VK_TAB, KeyboardKeyCode::Tab },
	{ VK_CLEAR, KeyboardKeyCode::Clear },
	{ VK_PAUSE, KeyboardKeyCode::Pause },
	{ VK_ESCAPE, KeyboardKeyCode::Esc },
	{ VK_DELETE, KeyboardKeyCode::Del },

	{ VK_UP, KeyboardKeyCode::Up },
	{ VK_DOWN, KeyboardKeyCode::Down },
	{ VK_LEFT, KeyboardKeyCode::Left },
	{ VK_RIGHT, KeyboardKeyCode::Right },
	{ VK_INSERT, KeyboardKeyCode::Insert },
	{ VK_HOME, KeyboardKeyCode::Home },
	{ VK_END, KeyboardKeyCode::End },
	{ VK_PRIOR, KeyboardKeyCode::PageUp },
	{ VK_NEXT, KeyboardKeyCode::PageDown },

	{ VK_NUMPAD0, KeyboardKeyCode::NumPad0 },
	{ VK_NUMPAD1, KeyboardKeyCode::NumPad1 },
	{ VK_NUMPAD2, KeyboardKeyCode::NumPad2 },
	{ VK_NUMPAD3, KeyboardKeyCode::NumPad3 },
	{ VK_NUMPAD4, KeyboardKeyCode::NumPad4 },
	{ VK_NUMPAD5, KeyboardKeyCode::NumPad5 },
	{ VK_NUMPAD6, KeyboardKeyCode::NumPad6 },
	{ VK_NUMPAD7, KeyboardKeyCode::NumPad7 },
	{ VK_NUMPAD8, KeyboardKeyCode::NumPad8 },
	{ VK_NUMPAD9, KeyboardKeyCode::NumPad9 },
	{ VK_ADD, KeyboardKeyCode::NumPadAdd },
	{ VK_SUBTRACT, KeyboardKeyCode::NumPadSub },
	{ VK_MULTIPLY, KeyboardKeyCode::NumPadMul },
	{ VK_DIVIDE, KeyboardKeyCode::NumPadDiv },
	{ VK_DECIMAL, KeyboardKeyCode::NumPadDot },
	{ VK_RETURN, KeyboardKeyCode::NumPadEnter },
	{ VK_SEPARATOR, KeyboardKeyCode::NumPadEq },

	{ VK_F1, KeyboardKeyCode::F1 },
	{ VK_F2, KeyboardKeyCode::F2 },
	{ VK_F3, KeyboardKeyCode::F3 },
	{ VK_F4, KeyboardKeyCode::F4 },
	{ VK_F5, KeyboardKeyCode::F5 },
	{ VK_F6, KeyboardKeyCode::F6 },
	{ VK_F7, KeyboardKeyCode::F7 },
	{ VK_F8, KeyboardKeyCode::F8 },
	{ VK_F9, KeyboardKeyCode::F9 },
	{ VK_F10, KeyboardKeyCode::F10 },
	{ VK_F11, KeyboardKeyCode::F11 },
	{ VK_F12, KeyboardKeyCode::F12 },

	{ VK_NUMLOCK, KeyboardKeyCode::NumLock },
	{ VK_CAPITAL, KeyboardKeyCode::CapsLock },
	{ VK_SCROLL, KeyboardKeyCode::ScrollLock },
	{ VK_LSHIFT, KeyboardKeyCode::LShift },
	{ VK_RSHIFT, KeyboardKeyCode::RShift },
	{ VK_LCONTROL, KeyboardKeyCode::LCtrl },
	{ VK_RCONTROL, KeyboardKeyCode::RCtrl },
	{ VK_LMENU, KeyboardKeyCode::LAlt },
	{ VK_RMENU, KeyboardKeyCode::RAlt },
	{ VK_LWIN, KeyboardKeyCode::LSuper },
	{ VK_RWIN, KeyboardKeyCode::RSuper }
};
